version: '3.8'

services:
  ollama:
    image: ollama/ollama
    # container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    environment:
      - OLLAMA_PORT=11434

  

volumes:
  ollama_data: